// AUTO-GENERATED by scripts/generate-std-catalogue.mjs from ../Std.fleaux
// Do not edit by hand.

export type StdParam = { name: string; type: string };

export type StdValueEntry = {
  qualifiedName: string;
  namespace: string;
  name: string;
  valueType: string;
};

export type StdFunctionEntry = {
  qualifiedName: string;
  namespace: string;
  name: string;
  params: StdParam[];
  returnType: string;
};

export const STD_VALUES: StdValueEntry[] = [
  {
    "qualifiedName": "Std.Half",
    "namespace": "Std",
    "name": "Half",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Third",
    "namespace": "Std",
    "name": "Third",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.TwoThirds",
    "namespace": "Std",
    "name": "TwoThirds",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Sixth",
    "namespace": "Std",
    "name": "Sixth",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ThreeQuarters",
    "namespace": "Std",
    "name": "ThreeQuarters",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootTwo",
    "namespace": "Std",
    "name": "RootTwo",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootThree",
    "namespace": "Std",
    "name": "RootThree",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.HalfRootTwo",
    "namespace": "Std",
    "name": "HalfRootTwo",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.LnTwo",
    "namespace": "Std",
    "name": "LnTwo",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.LnLnTwo",
    "namespace": "Std",
    "name": "LnLnTwo",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootLnFour",
    "namespace": "Std",
    "name": "RootLnFour",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivRootTwo",
    "namespace": "Std",
    "name": "OneDivRootTwo",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Pi",
    "namespace": "Std",
    "name": "Pi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.HalfPi",
    "namespace": "Std",
    "name": "HalfPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ThirdPi",
    "namespace": "Std",
    "name": "ThirdPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.SixthPi",
    "namespace": "Std",
    "name": "SixthPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.TwoPi",
    "namespace": "Std",
    "name": "TwoPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Tau",
    "namespace": "Std",
    "name": "Tau",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.TwoThirdsPi",
    "namespace": "Std",
    "name": "TwoThirdsPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ThreeQuartersPi",
    "namespace": "Std",
    "name": "ThreeQuartersPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.FourThirdsPi",
    "namespace": "Std",
    "name": "FourThirdsPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivTwoPi",
    "namespace": "Std",
    "name": "OneDivTwoPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivRootTwoPi",
    "namespace": "Std",
    "name": "OneDivRootTwoPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootPi",
    "namespace": "Std",
    "name": "RootPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootHalfPi",
    "namespace": "Std",
    "name": "RootHalfPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootTwoPi",
    "namespace": "Std",
    "name": "RootTwoPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.LogRootTwoPi",
    "namespace": "Std",
    "name": "LogRootTwoPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivRootPi",
    "namespace": "Std",
    "name": "OneDivRootPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootOneDivPi",
    "namespace": "Std",
    "name": "RootOneDivPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.PiMinusThree",
    "namespace": "Std",
    "name": "PiMinusThree",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.FourMinusPi",
    "namespace": "Std",
    "name": "FourMinusPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.PiPowE",
    "namespace": "Std",
    "name": "PiPowE",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.PiSqr",
    "namespace": "Std",
    "name": "PiSqr",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.PiSqrDivSix",
    "namespace": "Std",
    "name": "PiSqrDivSix",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.PiCubed",
    "namespace": "Std",
    "name": "PiCubed",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.CbrtPi",
    "namespace": "Std",
    "name": "CbrtPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivCbrtPi",
    "namespace": "Std",
    "name": "OneDivCbrtPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Log2E",
    "namespace": "Std",
    "name": "Log2E",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.E",
    "namespace": "Std",
    "name": "E",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ExpMinusHalf",
    "namespace": "Std",
    "name": "ExpMinusHalf",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ExpMinusOne",
    "namespace": "Std",
    "name": "ExpMinusOne",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.EPowPi",
    "namespace": "Std",
    "name": "EPowPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootE",
    "namespace": "Std",
    "name": "RootE",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Log10E",
    "namespace": "Std",
    "name": "Log10E",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivLog10E",
    "namespace": "Std",
    "name": "OneDivLog10E",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.LnTen",
    "namespace": "Std",
    "name": "LnTen",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Degree",
    "namespace": "Std",
    "name": "Degree",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Radian",
    "namespace": "Std",
    "name": "Radian",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.SinOne",
    "namespace": "Std",
    "name": "SinOne",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.CosOne",
    "namespace": "Std",
    "name": "CosOne",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.SinhOne",
    "namespace": "Std",
    "name": "SinhOne",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.CoshOne",
    "namespace": "Std",
    "name": "CoshOne",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Phi",
    "namespace": "Std",
    "name": "Phi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.LnPhi",
    "namespace": "Std",
    "name": "LnPhi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivLnPhi",
    "namespace": "Std",
    "name": "OneDivLnPhi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Euler",
    "namespace": "Std",
    "name": "Euler",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.OneDivEuler",
    "namespace": "Std",
    "name": "OneDivEuler",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.EulerSqr",
    "namespace": "Std",
    "name": "EulerSqr",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ZetaTwo",
    "namespace": "Std",
    "name": "ZetaTwo",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ZetaThree",
    "namespace": "Std",
    "name": "ZetaThree",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Catalan",
    "namespace": "Std",
    "name": "Catalan",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Glaisher",
    "namespace": "Std",
    "name": "Glaisher",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.Khinchin",
    "namespace": "Std",
    "name": "Khinchin",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.ExtremeValueSkewness",
    "namespace": "Std",
    "name": "ExtremeValueSkewness",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RayleighSkewness",
    "namespace": "Std",
    "name": "RayleighSkewness",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RayleighKurtosis",
    "namespace": "Std",
    "name": "RayleighKurtosis",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RayleighKurtosisExcess",
    "namespace": "Std",
    "name": "RayleighKurtosisExcess",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.TwoDivPi",
    "namespace": "Std",
    "name": "TwoDivPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.RootTwoDivPi",
    "namespace": "Std",
    "name": "RootTwoDivPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.QuarterPi",
    "namespace": "Std",
    "name": "QuarterPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.InvPi",
    "namespace": "Std",
    "name": "InvPi",
    "valueType": "Number"
  },
  {
    "qualifiedName": "Std.TwoDivRootPi",
    "namespace": "Std",
    "name": "TwoDivRootPi",
    "valueType": "Number"
  }
];

export const STD_FUNCTIONS: StdFunctionEntry[] = [
  {
    "qualifiedName": "Std.Println",
    "namespace": "Std",
    "name": "Println",
    "params": [
      {
        "name": "args",
        "type": "Any..."
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Printf",
    "namespace": "Std",
    "name": "Printf",
    "params": [
      {
        "name": "fmt_str",
        "type": "String"
      },
      {
        "name": "args",
        "type": "Any..."
      }
    ],
    "returnType": "Tuple(String, Any...)"
  },
  {
    "qualifiedName": "Std.Input",
    "namespace": "Std",
    "name": "Input",
    "params": [],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Exit",
    "namespace": "Std",
    "name": "Exit",
    "params": [
      {
        "name": "code",
        "type": "Number"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Add",
    "namespace": "Std",
    "name": "Add",
    "params": [
      {
        "name": "lhs",
        "type": "Number"
      },
      {
        "name": "rhs",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Subtract",
    "namespace": "Std",
    "name": "Subtract",
    "params": [
      {
        "name": "lhs",
        "type": "Number"
      },
      {
        "name": "rhs",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Multiply",
    "namespace": "Std",
    "name": "Multiply",
    "params": [
      {
        "name": "lhs",
        "type": "Number"
      },
      {
        "name": "rhs",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Divide",
    "namespace": "Std",
    "name": "Divide",
    "params": [
      {
        "name": "lhs",
        "type": "Number"
      },
      {
        "name": "rhs",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Mod",
    "namespace": "Std",
    "name": "Mod",
    "params": [
      {
        "name": "lhs",
        "type": "Number"
      },
      {
        "name": "rhs",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Pow",
    "namespace": "Std",
    "name": "Pow",
    "params": [
      {
        "name": "lhs",
        "type": "Number"
      },
      {
        "name": "rhs",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Sqrt",
    "namespace": "Std",
    "name": "Sqrt",
    "params": [
      {
        "name": "val",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Tan",
    "namespace": "Std",
    "name": "Tan",
    "params": [
      {
        "name": "val",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Sin",
    "namespace": "Std",
    "name": "Sin",
    "params": [
      {
        "name": "val",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Cos",
    "namespace": "Std",
    "name": "Cos",
    "params": [
      {
        "name": "val",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.GreaterThan",
    "namespace": "Std",
    "name": "GreaterThan",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.LessThan",
    "namespace": "Std",
    "name": "LessThan",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.GreaterOrEqual",
    "namespace": "Std",
    "name": "GreaterOrEqual",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.LessOrEqual",
    "namespace": "Std",
    "name": "LessOrEqual",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Equal",
    "namespace": "Std",
    "name": "Equal",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.NotEqual",
    "namespace": "Std",
    "name": "NotEqual",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Not",
    "namespace": "Std",
    "name": "Not",
    "params": [
      {
        "name": "val",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.And",
    "namespace": "Std",
    "name": "And",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Or",
    "namespace": "Std",
    "name": "Or",
    "params": [
      {
        "name": "lhs",
        "type": "Any"
      },
      {
        "name": "rhs",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Select",
    "namespace": "Std",
    "name": "Select",
    "params": [
      {
        "name": "condition",
        "type": "Bool"
      },
      {
        "name": "true_val",
        "type": "Any"
      },
      {
        "name": "false_val",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Match",
    "namespace": "Std",
    "name": "Match",
    "params": [
      {
        "name": "value",
        "type": "Any"
      },
      {
        "name": "cases",
        "type": "Any..."
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Result.Ok",
    "namespace": "Std.Result",
    "name": "Ok",
    "params": [
      {
        "name": "value",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Bool, Any)"
  },
  {
    "qualifiedName": "Std.Result.Err",
    "namespace": "Std.Result",
    "name": "Err",
    "params": [
      {
        "name": "error",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Bool, Any)"
  },
  {
    "qualifiedName": "Std.Result.Tag",
    "namespace": "Std.Result",
    "name": "Tag",
    "params": [
      {
        "name": "result",
        "type": "Tuple(Bool, Any)"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Result.Payload",
    "namespace": "Std.Result",
    "name": "Payload",
    "params": [
      {
        "name": "result",
        "type": "Tuple(Bool, Any)"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Result.IsOk",
    "namespace": "Std.Result",
    "name": "IsOk",
    "params": [
      {
        "name": "result",
        "type": "Tuple(Bool, Any)"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Result.IsErr",
    "namespace": "Std.Result",
    "name": "IsErr",
    "params": [
      {
        "name": "result",
        "type": "Tuple(Bool, Any)"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Result.Unwrap",
    "namespace": "Std.Result",
    "name": "Unwrap",
    "params": [
      {
        "name": "result",
        "type": "Tuple(Bool, Any)"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Result.UnwrapErr",
    "namespace": "Std.Result",
    "name": "UnwrapErr",
    "params": [
      {
        "name": "result",
        "type": "Tuple(Bool, Any)"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Try",
    "namespace": "Std",
    "name": "Try",
    "params": [
      {
        "name": "value",
        "type": "Any"
      },
      {
        "name": "func",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Bool, Any)"
  },
  {
    "qualifiedName": "Std.Exp.Parallel",
    "namespace": "Std.Exp",
    "name": "Parallel",
    "params": [
      {
        "name": "items",
        "type": "Tuple(Any...)"
      },
      {
        "name": "func",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Bool, Any)"
  },
  {
    "qualifiedName": "Std.Apply",
    "namespace": "Std",
    "name": "Apply",
    "params": [
      {
        "name": "value",
        "type": "Any"
      },
      {
        "name": "func",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Branch",
    "namespace": "Std",
    "name": "Branch",
    "params": [
      {
        "name": "condition",
        "type": "Bool"
      },
      {
        "name": "value",
        "type": "Any"
      },
      {
        "name": "true_func",
        "type": "Any"
      },
      {
        "name": "false_func",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Loop",
    "namespace": "Std",
    "name": "Loop",
    "params": [
      {
        "name": "state",
        "type": "Any"
      },
      {
        "name": "continue_func",
        "type": "Any"
      },
      {
        "name": "step_func",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.LoopN",
    "namespace": "Std",
    "name": "LoopN",
    "params": [
      {
        "name": "state",
        "type": "Any"
      },
      {
        "name": "continue_func",
        "type": "Any"
      },
      {
        "name": "step_func",
        "type": "Any"
      },
      {
        "name": "max_iters",
        "type": "Number"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.UnaryPlus",
    "namespace": "Std",
    "name": "UnaryPlus",
    "params": [
      {
        "name": "val",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.UnaryMinus",
    "namespace": "Std",
    "name": "UnaryMinus",
    "params": [
      {
        "name": "val",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.ToString",
    "namespace": "Std",
    "name": "ToString",
    "params": [
      {
        "name": "val",
        "type": "Any"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Math.Sqrt",
    "namespace": "Std.Math",
    "name": "Sqrt",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Sin",
    "namespace": "Std.Math",
    "name": "Sin",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Cos",
    "namespace": "Std.Math",
    "name": "Cos",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Tan",
    "namespace": "Std.Math",
    "name": "Tan",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Floor",
    "namespace": "Std.Math",
    "name": "Floor",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Ceil",
    "namespace": "Std.Math",
    "name": "Ceil",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Abs",
    "namespace": "Std.Math",
    "name": "Abs",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Log",
    "namespace": "Std.Math",
    "name": "Log",
    "params": [
      {
        "name": "x",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Math.Clamp",
    "namespace": "Std.Math",
    "name": "Clamp",
    "params": [
      {
        "name": "x",
        "type": "Number"
      },
      {
        "name": "lo",
        "type": "Number"
      },
      {
        "name": "hi",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.String.Upper",
    "namespace": "Std.String",
    "name": "Upper",
    "params": [
      {
        "name": "s",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Lower",
    "namespace": "Std.String",
    "name": "Lower",
    "params": [
      {
        "name": "s",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Trim",
    "namespace": "Std.String",
    "name": "Trim",
    "params": [
      {
        "name": "s",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.TrimStart",
    "namespace": "Std.String",
    "name": "TrimStart",
    "params": [
      {
        "name": "s",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.TrimEnd",
    "namespace": "Std.String",
    "name": "TrimEnd",
    "params": [
      {
        "name": "s",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Split",
    "namespace": "Std.String",
    "name": "Split",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "sep",
        "type": "String"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.String.Join",
    "namespace": "Std.String",
    "name": "Join",
    "params": [
      {
        "name": "sep",
        "type": "String"
      },
      {
        "name": "parts",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Replace",
    "namespace": "Std.String",
    "name": "Replace",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "old",
        "type": "String"
      },
      {
        "name": "new",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Contains",
    "namespace": "Std.String",
    "name": "Contains",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "sub",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.String.StartsWith",
    "namespace": "Std.String",
    "name": "StartsWith",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "prefix",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.String.EndsWith",
    "namespace": "Std.String",
    "name": "EndsWith",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "suffix",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.String.Length",
    "namespace": "Std.String",
    "name": "Length",
    "params": [
      {
        "name": "s",
        "type": "String"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.String.CharAt",
    "namespace": "Std.String",
    "name": "CharAt",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "index",
        "type": "Number"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Slice",
    "namespace": "Std.String",
    "name": "Slice",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "start",
        "type": "Number"
      },
      {
        "name": "stop",
        "type": "Number"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Find",
    "namespace": "Std.String",
    "name": "Find",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "sub",
        "type": "String"
      },
      {
        "name": "start",
        "type": "Number"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.String.Format",
    "namespace": "Std.String",
    "name": "Format",
    "params": [
      {
        "name": "fmt_str",
        "type": "String"
      },
      {
        "name": "args",
        "type": "Any..."
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Regex.IsMatch",
    "namespace": "Std.String.Regex",
    "name": "IsMatch",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "pattern",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.String.Regex.Find",
    "namespace": "Std.String.Regex",
    "name": "Find",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "pattern",
        "type": "String"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.String.Regex.Replace",
    "namespace": "Std.String.Regex",
    "name": "Replace",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "pattern",
        "type": "String"
      },
      {
        "name": "repl",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.String.Regex.Split",
    "namespace": "Std.String.Regex",
    "name": "Split",
    "params": [
      {
        "name": "s",
        "type": "String"
      },
      {
        "name": "pattern",
        "type": "String"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.OS.Cwd",
    "namespace": "Std.OS",
    "name": "Cwd",
    "params": [],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.OS.Home",
    "namespace": "Std.OS",
    "name": "Home",
    "params": [],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.OS.TempDir",
    "namespace": "Std.OS",
    "name": "TempDir",
    "params": [],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.OS.MakeTempFile",
    "namespace": "Std.OS",
    "name": "MakeTempFile",
    "params": [],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.OS.MakeTempDir",
    "namespace": "Std.OS",
    "name": "MakeTempDir",
    "params": [],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.OS.Env",
    "namespace": "Std.OS",
    "name": "Env",
    "params": [
      {
        "name": "name",
        "type": "String"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.OS.HasEnv",
    "namespace": "Std.OS",
    "name": "HasEnv",
    "params": [
      {
        "name": "name",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.OS.SetEnv",
    "namespace": "Std.OS",
    "name": "SetEnv",
    "params": [
      {
        "name": "name",
        "type": "String"
      },
      {
        "name": "value",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.OS.UnsetEnv",
    "namespace": "Std.OS",
    "name": "UnsetEnv",
    "params": [
      {
        "name": "name",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.OS.IsWindows",
    "namespace": "Std.OS",
    "name": "IsWindows",
    "params": [],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.OS.IsLinux",
    "namespace": "Std.OS",
    "name": "IsLinux",
    "params": [],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.OS.IsMacOS",
    "namespace": "Std.OS",
    "name": "IsMacOS",
    "params": [],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Path.Join",
    "namespace": "Std.Path",
    "name": "Join",
    "params": [
      {
        "name": "lhs",
        "type": "String"
      },
      {
        "name": "rhs",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.Normalize",
    "namespace": "Std.Path",
    "name": "Normalize",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.Basename",
    "namespace": "Std.Path",
    "name": "Basename",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.Dirname",
    "namespace": "Std.Path",
    "name": "Dirname",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.Exists",
    "namespace": "Std.Path",
    "name": "Exists",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Path.IsFile",
    "namespace": "Std.Path",
    "name": "IsFile",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Path.IsDir",
    "namespace": "Std.Path",
    "name": "IsDir",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Path.Absolute",
    "namespace": "Std.Path",
    "name": "Absolute",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.Extension",
    "namespace": "Std.Path",
    "name": "Extension",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.Stem",
    "namespace": "Std.Path",
    "name": "Stem",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.WithExtension",
    "namespace": "Std.Path",
    "name": "WithExtension",
    "params": [
      {
        "name": "path",
        "type": "String"
      },
      {
        "name": "ext",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Path.WithBasename",
    "namespace": "Std.Path",
    "name": "WithBasename",
    "params": [
      {
        "name": "path",
        "type": "String"
      },
      {
        "name": "name",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.File.ReadText",
    "namespace": "Std.File",
    "name": "ReadText",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.File.WriteText",
    "namespace": "Std.File",
    "name": "WriteText",
    "params": [
      {
        "name": "path",
        "type": "String"
      },
      {
        "name": "text",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.File.AppendText",
    "namespace": "Std.File",
    "name": "AppendText",
    "params": [
      {
        "name": "path",
        "type": "String"
      },
      {
        "name": "text",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.File.ReadLines",
    "namespace": "Std.File",
    "name": "ReadLines",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.File.Delete",
    "namespace": "Std.File",
    "name": "Delete",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.File.Size",
    "namespace": "Std.File",
    "name": "Size",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Dir.Create",
    "namespace": "Std.Dir",
    "name": "Create",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "String"
  },
  {
    "qualifiedName": "Std.Dir.Delete",
    "namespace": "Std.Dir",
    "name": "Delete",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Dir.List",
    "namespace": "Std.Dir",
    "name": "List",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Dir.ListFull",
    "namespace": "Std.Dir",
    "name": "ListFull",
    "params": [
      {
        "name": "path",
        "type": "String"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Append",
    "namespace": "Std.Tuple",
    "name": "Append",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "item",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Prepend",
    "namespace": "Std.Tuple",
    "name": "Prepend",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "item",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Reverse",
    "namespace": "Std.Tuple",
    "name": "Reverse",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Contains",
    "namespace": "Std.Tuple",
    "name": "Contains",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "item",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Tuple.Zip",
    "namespace": "Std.Tuple",
    "name": "Zip",
    "params": [
      {
        "name": "a",
        "type": "Tuple(Any...)"
      },
      {
        "name": "b",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Map",
    "namespace": "Std.Tuple",
    "name": "Map",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "func",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Filter",
    "namespace": "Std.Tuple",
    "name": "Filter",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "pred",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Sort",
    "namespace": "Std.Tuple",
    "name": "Sort",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Unique",
    "namespace": "Std.Tuple",
    "name": "Unique",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Tuple.Min",
    "namespace": "Std.Tuple",
    "name": "Min",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Tuple.Max",
    "namespace": "Std.Tuple",
    "name": "Max",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Tuple.Reduce",
    "namespace": "Std.Tuple",
    "name": "Reduce",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "initial",
        "type": "Any"
      },
      {
        "name": "func",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Tuple.FindIndex",
    "namespace": "Std.Tuple",
    "name": "FindIndex",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "pred",
        "type": "Any"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Tuple.Any",
    "namespace": "Std.Tuple",
    "name": "Any",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "pred",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Tuple.All",
    "namespace": "Std.Tuple",
    "name": "All",
    "params": [
      {
        "name": "t",
        "type": "Tuple(Any...)"
      },
      {
        "name": "pred",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Tuple.Range",
    "namespace": "Std.Tuple",
    "name": "Range",
    "params": [
      {
        "name": "stop",
        "type": "Number"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Take",
    "namespace": "Std",
    "name": "Take",
    "params": [
      {
        "name": "tuple",
        "type": "Tuple(Any...)"
      },
      {
        "name": "count",
        "type": "Number"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Drop",
    "namespace": "Std",
    "name": "Drop",
    "params": [
      {
        "name": "tuple",
        "type": "Tuple(Any...)"
      },
      {
        "name": "count",
        "type": "Number"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.ElementAt",
    "namespace": "Std",
    "name": "ElementAt",
    "params": [
      {
        "name": "tuple",
        "type": "Tuple(Any...)"
      },
      {
        "name": "count",
        "type": "Number"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Length",
    "namespace": "Std",
    "name": "Length",
    "params": [
      {
        "name": "tuple",
        "type": "Tuple(Any...)"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.Slice",
    "namespace": "Std",
    "name": "Slice",
    "params": [
      {
        "name": "tuple",
        "type": "Tuple(Any...)"
      },
      {
        "name": "stop",
        "type": "Number"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.ToNum",
    "namespace": "Std",
    "name": "ToNum",
    "params": [
      {
        "name": "val",
        "type": "String"
      }
    ],
    "returnType": "Number"
  },
  {
    "qualifiedName": "Std.GetArgs",
    "namespace": "Std",
    "name": "GetArgs",
    "params": [],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.File.Open",
    "namespace": "Std.File",
    "name": "Open",
    "params": [
      {
        "name": "path",
        "type": "String"
      },
      {
        "name": "mode",
        "type": "String"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.File.ReadLine",
    "namespace": "Std.File",
    "name": "ReadLine",
    "params": [
      {
        "name": "handle",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any, String, Bool)"
  },
  {
    "qualifiedName": "Std.File.ReadChunk",
    "namespace": "Std.File",
    "name": "ReadChunk",
    "params": [
      {
        "name": "handle",
        "type": "Any"
      },
      {
        "name": "nbytes",
        "type": "Number"
      }
    ],
    "returnType": "Tuple(Any, String, Bool)"
  },
  {
    "qualifiedName": "Std.File.WriteChunk",
    "namespace": "Std.File",
    "name": "WriteChunk",
    "params": [
      {
        "name": "handle",
        "type": "Any"
      },
      {
        "name": "data",
        "type": "String"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.File.Flush",
    "namespace": "Std.File",
    "name": "Flush",
    "params": [
      {
        "name": "handle",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.File.Close",
    "namespace": "Std.File",
    "name": "Close",
    "params": [
      {
        "name": "handle",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.File.WithOpen",
    "namespace": "Std.File",
    "name": "WithOpen",
    "params": [
      {
        "name": "path",
        "type": "String"
      },
      {
        "name": "mode",
        "type": "String"
      },
      {
        "name": "func",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Wrap",
    "namespace": "Std",
    "name": "Wrap",
    "params": [
      {
        "name": "val",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any)"
  },
  {
    "qualifiedName": "Std.Unwrap",
    "namespace": "Std",
    "name": "Unwrap",
    "params": [
      {
        "name": "tuple",
        "type": "Tuple(Any)"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.Create",
    "namespace": "Std.Dict",
    "name": "Create",
    "params": [],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.Set",
    "namespace": "Std.Dict",
    "name": "Set",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      },
      {
        "name": "key",
        "type": "Any"
      },
      {
        "name": "value",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.Get",
    "namespace": "Std.Dict",
    "name": "Get",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      },
      {
        "name": "key",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.GetDefault",
    "namespace": "Std.Dict",
    "name": "GetDefault",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      },
      {
        "name": "key",
        "type": "Any"
      },
      {
        "name": "default",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.Contains",
    "namespace": "Std.Dict",
    "name": "Contains",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      },
      {
        "name": "key",
        "type": "Any"
      }
    ],
    "returnType": "Bool"
  },
  {
    "qualifiedName": "Std.Dict.Delete",
    "namespace": "Std.Dict",
    "name": "Delete",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      },
      {
        "name": "key",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.Keys",
    "namespace": "Std.Dict",
    "name": "Keys",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Dict.Values",
    "namespace": "Std.Dict",
    "name": "Values",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Dict.Entries",
    "namespace": "Std.Dict",
    "name": "Entries",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      }
    ],
    "returnType": "Tuple(Any...)"
  },
  {
    "qualifiedName": "Std.Dict.Clear",
    "namespace": "Std.Dict",
    "name": "Clear",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      }
    ],
    "returnType": "Any"
  },
  {
    "qualifiedName": "Std.Dict.Length",
    "namespace": "Std.Dict",
    "name": "Length",
    "params": [
      {
        "name": "dict",
        "type": "Any"
      }
    ],
    "returnType": "Number"
  }
];

export const STD_VALUES_BY_NAMESPACE: Map<string, StdValueEntry[]> = (() => {
  const map = new Map<string, StdValueEntry[]>();
  for (const value of STD_VALUES) {
    const group = map.get(value.namespace) ?? [];
    group.push(value);
    map.set(value.namespace, group);
  }
  return map;
})();

export const STD_BY_NAMESPACE: Map<string, StdFunctionEntry[]> = (() => {
  const map = new Map<string, StdFunctionEntry[]>();
  for (const fn of STD_FUNCTIONS) {
    const group = map.get(fn.namespace) ?? [];
    group.push(fn);
    map.set(fn.namespace, group);
  }
  return map;
})();

export const STD_NAMESPACES = [
  "Std",
  "Std.Result",
  "Std.Exp",
  "Std.Math",
  "Std.String",
  "Std.String.Regex",
  "Std.OS",
  "Std.Path",
  "Std.File",
  "Std.Dir",
  "Std.Tuple",
  "Std.Dict"
] as const;
